site_name: OHSU BioData Club GitHub Pages Tutorial
theme: material
plugins:
    - search
docs_dir: rtd
nav:
    - What is OHSU BioData Club?: index.md
    - The Workshop:
        - Introduction: workshop/introduction.md
        - First Steps: workshop/first-steps.md
        - Your Bio: workshop/your-bio.md
        - Basic Markdown: workshop/basic-markdown.md
        - Uploading a Bio Photo: workshop/bio-photo.md
        - Tips & Tricks: workshop/tips-tricks.md
    - Advanced Topics:
        - Adding a menu item: advanced/add-menu.md
        - Aesthetics & Appearance: advanced/aesthetics.md
        - Linking External Photos: advanced/external-photos.md
        - Blog Posts: advanced/blog-posts.md
        - Embedding Presentations: advanced/presentations.md
        - Custom Themes: advanced/themes.md
        - HTML in Markdown: advanced/html-markdown.md
        - Updating Favorite Icon: advanced/favicon.md
        - Using GitHub Desktop: advanced/github-desktop.md
